(function(){
  const CASES=['Називний','Родовий','Давальний','Знахідний','Орудний','Місцевий','Кличний'];
  function words(v){return String(v||'').trim().replace(/\s+/g,' ').split(' ').filter(Boolean)}
  const maleFirst={ 'Ростислав':{r:'Ростислава',d:'Ростиславу',a:'Ростислава',i:'Ростиславом',l:'Ростиславі',v:'Ростиславе'} };
  const malePat={ 'Сергійович':{r:'Сергійовича',d:'Сергійовичу',a:'Сергійовича',i:'Сергійовичем',l:'Сергійовичу',v:'Сергійовичу'} };
  function firstDecl(w){const m=maleFirst[w];if(m)return m;if(/ій$/i.test(w))return{r:w.replace(/ій$/i,'ія'),d:w.replace(/ій$/i,'ію'),a:w.replace(/ій$/i,'ія'),i:w.replace(/ій$/i,'ієм'),l:w.replace(/ій$/i,'ію'),v:w.replace(/ій$/i,'ію')};if(/[бвгґджзклмнпрстфхцчшщ]$/i.test(w))return{r:w+'а',d:w+'у',a:w+'а',i:w+'ом',l:w+'і',v:w+'е'};return{r:w,d:w,a:w,i:w,l:w,v:w};}
  function patDecl(w){const m=malePat[w];return m||{r:w,d:w,a:w,i:w,l:w,v:w};}
  function surnameDecl(s,g){if(g==='male'){if(/енко$/i.test(s))return{n:s,r:s.replace(/енко$/i,'енка'),d:s.replace(/енко$/i,'енку'),a:s.replace(/енко$/i,'енка'),i:s.replace(/енко$/i,'енком'),l:s.replace(/енко$/i,'енку'),v:s};if(/[бвгґджзклмнпрстфхцчшщ]$/i.test(s))return{n:s,r:s+'а',d:s+'у',a:s+'а',i:s+'ом',l:s+'і',v:s};}return{n:s,r:s,d:s,a:s,i:s,l:s,v:s};}
  function normalize(parts){if(parts.length<2)return null;let[s,f,p]=parts;let gender=/[аеє]вич$/i.test(p)?'male':(/[івна]$/i.test(p)?'female':'male');if(gender==='male'&&/енка$/i.test(s))s=s.replace(/енка$/i,'енко');const sd=surnameDecl(s,gender),fd=firstDecl(f),pd=patDecl(p);return{gender,cases:{'Називний':[sd.n,f,p].join(' '),'Родовий':[sd.r,fd.r,pd.r].join(' '),'Давальний':[sd.d,fd.d,pd.d].join(' '),'Знахідний':[sd.a,fd.a,pd.a].join(' '),'Орудний':[sd.i,fd.i,pd.i].join(' '),'Місцевий':[sd.l,fd.l,pd.l].join(' '),'Кличний':[sd.v,fd.v,pd.v].join(' ')}};}
  function findField(labelText){const labels=[...document.querySelectorAll('label')];const l=labels.find(x=>x.textContent.trim().toLowerCase()===labelText.toLowerCase());if(!l)return null;if(l.htmlFor){const el=document.getElementById(l.htmlFor);if(el)return el;}let n=l.nextElementSibling;while(n){if(/INPUT|TEXTAREA|SELECT/.test(n.tagName))return n;n=n.nextElementSibling;}const p=l.parentElement;return p?p.querySelector('input,textarea,select'):null;}
  function run(){const full=document.querySelector('input[name="full_name"]');if(!full||!full.value.trim())return;const data=normalize(words(full.value));if(!data)return;CASES.forEach(c=>{const el=findField(c);if(el&&document.activeElement!==el)el.value=data.cases[c];});const box=[...document.querySelectorAll('*')].find(e=>e.children.length===0&&e.textContent.trim()==='Стать: не визначено');if(box)box.textContent='Стать: '+(data.gender==='male'?'чоловіча':'жіноча');}
  document.addEventListener('input',e=>{if(e.target&&e.target.name==='full_name')setTimeout(run,0)});new MutationObserver(()=>setTimeout(run,0)).observe(document.body,{childList:true,subtree:true});setInterval(run,800);
})();